import { writeFileSync, existsSync } from 'fs';
import { join } from 'path';
import { requireProjectRoot, loadKey } from '../keystore.js';
import { loadConfig } from '../config.js';
import { readEncEnv } from '../enc.js';
import { ok, warn, fatal, bold, dim } from '../ui.js';

export async function template(options) {
  const projectRoot = requireProjectRoot();
  const key         = loadKey(projectRoot);
  const config      = loadConfig(projectRoot);

  // Merge keys from all envs (union), sorted
  const allKeys = [...new Set(
    config.envs.flatMap(envName => Object.keys(readEncEnv(projectRoot, envName, key)))
  )].sort();

  if (allKeys.length === 0) {
    warn('No variables found — nothing to template.');
    return;
  }

  const outPath = join(projectRoot, options.output ?? '.env.example');

  if (existsSync(outPath) && !options.force) {
    fatal(`${outPath} already exists. Use --force to overwrite.`);
  }

  const projectName = config.project ?? 'your-project';
  const envList     = config.envs.join(', ');

  const lines = [
    `# .env.example — generated by envgit`,
    `# Project : ${projectName}`,
    `# Envs    : ${envList}`,
    `#`,
    `# Do not put real values here. This file is safe to commit.`,
    `# To get the real values: envgit join <token> --code <passphrase>`,
    `#                    then: envgit unpack dev`,
    ``,
    ...allKeys.map(k => `${k}=`),
    ``,
  ].join('\n');

  writeFileSync(outPath, lines, 'utf8');

  console.log('');
  ok(`Generated ${dim(outPath)} with ${allKeys.length} key${allKeys.length !== 1 ? 's' : ''}`);
  console.log(dim(`  Envs scanned: ${envList}`));
  console.log('');
  console.log(dim(`  Commit it:  git add ${options.output ?? '.env.example'} && git commit -m "chore: update .env.example"`));
  console.log('');
}
